autotools: Check for pthread library in system

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3305,8 +3305,7 @@ ac_fn_c_check_header_mongrel "$LINENO" "ncurses.h" "ac_cv_header_ncurses_h" "$ac
 if test "x$ac_cv_header_ncurses_h" = xyes; then :
 
 else
-  { $as_echo "$as_me:${as_lineno-$LINENO}: result: ncurses.h not found" >&5
-$as_echo "ncurses.h not found" >&6; }
+  echo "ncurses.h not found"; exit 1
 fi
 
 
@@ -3349,8 +3348,49 @@ $as_echo "$ac_cv_lib_ncurses_initscr" >&6; }
 if test "x$ac_cv_lib_ncurses_initscr" = xyes; then :
   :
 else
-  { $as_echo "$as_me:${as_lineno-$LINENO}: result: Library ncurses not found" >&5
-$as_echo "Library ncurses not found" >&6; }
+  echo "pthread library not found" ; exit 1
+fi
+
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for pthread_create in -lpthread" >&5
+$as_echo_n "checking for pthread_create in -lpthread... " >&6; }
+if ${ac_cv_lib_pthread_pthread_create+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lpthread  $LIBS"
+cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char pthread_create ();
+int
+main ()
+{
+return pthread_create ();
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_link "$LINENO"; then :
+  ac_cv_lib_pthread_pthread_create=yes
+else
+  ac_cv_lib_pthread_pthread_create=no
+fi
+rm -f core conftest.err conftest.$ac_objext \
+    conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_pthread_pthread_create" >&5
+$as_echo "$ac_cv_lib_pthread_pthread_create" >&6; }
+if test "x$ac_cv_lib_pthread_pthread_create" = xyes; then :
+  :
+else
+   echo "pthread library not found" ; exit 1
 fi
 
 am__api_version='1.13'
